apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: opensearch
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/component: opensearch-cluster-master
    app.kubernetes.io/instance: opensearch
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: opensearch
    app.kubernetes.io/version: 2.19.1
    helm.sh/chart: opensearch-2.32.0
  name: opensearch-cluster-master
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 9200
    protocol: TCP
    targetPort: 9200
    nodePort: 31113
  - name: transport
    port: 9300
    protocol: TCP
    targetPort: 9300
  - name: metrics
    port: 9600
    protocol: TCP
    targetPort: 9600
  selector:
    app.kubernetes.io/instance: opensearch
    app.kubernetes.io/name: opensearch
  sessionAffinity: None
  type: NodePort